# Generated by Django 4.2.30 on 2026-09-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_type', models.CharField(choices=[('PICKUP', 'Pickup Inspection'), ('DROPOFF', 'Drop-off Inspection')], max_length=10)),
                ('front_photo', models.ImageField(upload_to='checkin_photos/')),
                ('rear_photo', models.ImageField(upload_to='checkin_photos/')),
                ('left_photo', models.ImageField(upload_to='checkin_photos/')),
                ('right_photo', models.ImageField(upload_to='checkin_photos/')),
                ('odometer_reading', models.IntegerField()),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='bookings.booking')),
            ],
        ),
    ]
